fix: authentication check for the chatbot and review pages
CarciDev/SvelteShip-SOEN-343 pull request #34
Opened 2024-11-24 19:56 UTC by GolimarGit

### 🛠 Proposed Changes:

The `NavBar` navigation links use a mouse event instead of directly changing the `href`.
Session token checks added to the chatbot and review routes.

### 📝 Details:

- `"src/lib/components/NavBar.svelte"`: the `TabAnchor` tag uses the `on:click={...}` mouse event rather than `href={href.link}`
- `"src/routes/api/chatbot/+server.ts"`: session retrieved and verified in POST method
- `"src/routes/review/+page.svelte"`: page redirect check added
- `"src/routes/api/review/+server.ts"`: session retrieved and verified in POST method

### 🔗 Related Issue(s):

N/A

2024-11-24 22:16 UTC, Verdone commented
Try running `npm run lint` and `npm run format`, then committing the necessary changes.

2024-11-24 23:02 UTC, GolimarGit commented
the code should be _prettier_ now :pepe_laugh:

2024-11-26 14:35 UTC, briantkatch requested changes
- Must include Prisma migration
- Do not manually decode the cookie; use the local provided by hooks.server.ts

2024-11-26 14:35 UTC, briantkatch commented on prisma/schema/Review.prisma
If you're changing the schema, you need to include a Prisma migration.

2024-11-26 14:35 UTC, briantkatch commented on src/routes/api/review/+server.ts
You don't need to validate the session yourself to check auth (and the cookie isn't called "session"). Use the local provided by hooks.server.ts.

2024-11-26 14:36 UTC, briantkatch commented
See the server code in routes/admin/page.server.ts for an example of imposing an auth requirement.

2024-11-26 19:01 UTC, Niravanaa commented
Authentication checks do not need to be done as the pages are already auth-protected through `hooks.server.ts`.

The schema is also being changed, but that is not what the intended scope of the PR should be.

The only change that needs to be done is the TabAnchor's on:click event being changed, nothing else really.

I'd recommend opening a new PR with that sole fix, instead of reverting any of the changes done in this PR

@GolimarGit

2024-11-26 21:04 UTC, GolimarGit commented
I did not intend to modify the schema; it was probably changed from the `npx prettier --write` ([commit details](https://github.com/SvelteShipSolutions/SvelteShip-SOEN-343/pull/34/commits/25a54258a02f1e79bac91defb358ff3f131537ef)).
If authentication checks do not need to be done directly in the separate pages, I will make a new branch that just changes the `on:click` event in the `TabAnchor` in `src/lib/components/NavBar.svelte`.
My fault gang.

2024-11-26 21:04 UTC, closed without merging